name: Deploy Docker Image to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-image:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GH_TOKEN}}

          - name: 'Build & Publish Uwuifier Image'
            run: |
              docker build . --tag ghcr.io/artificialbutter/uwuifierbot:latest
              docker push ghcr.io/artificialbutter/uwuifierbot:latest